try:
    print("Raising Exception........")
    raise ValueError
finally:
    print("performing clean up in finally........")
